builds:
- id: core-provider-dev
  main: main.go
  dir: . 
  env:
  - CGO_ENABLED=0
  - CORE_PROVIDER_DEBUG=true
  ldflags:
  - -s -w
  - -extldflags "-static"
defaultPlatforms:
- linux/arm64
- linux/amd64
defaultBaseImage: golang:1.25.3-alpine