apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-inspector
  namespace: demo-system
  labels:
    app: chart-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-inspector
  template:
    metadata:
      labels:
        app: chart-inspector
    spec:
      serviceAccountName: chart-inspector-sa
      containers:
      - name: chart-inspector-container
        image: ghcr.io/krateoplatformops/chart-inspector:0.0.1
        args:
          - "-debug"
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: chart-inspector-service
  namespace: demo-system
spec:
  selector:
    app: chart-inspector
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chart-inspector-viewer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chart-inspector-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chart-inspector-viewer
subjects:
- kind: ServiceAccount
  name: chart-inspector-sa
  namespace: demo-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chart-inspector-sa
  namespace: demo-system