apiVersion: v1
kind: Service
metadata:
  name: core-provider-webhook-service
  namespace: demo-system
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app: core-provider-dev