apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .resource }}-{{ .apiVersion }}-controller
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ .resource }}-{{ .apiVersion }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: krateoplatformops
    app.kubernetes.io/managed-by: krateo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ .namespace }}
      labels:
        app.kubernetes.io/name: {{ .name }}
    spec:
      containers:
      - name: {{ .resource }}-{{ .apiVersion }}-controller
        image: ghcr.io/krateoplatformops/composition-dynamic-controller:{{ or .tag "0.5.0" }}
        imagePullPolicy: IfNotPresent
        env: 
        - name: HOME # home should be set to /tmp or any other writable directory to avoid permission issues with helm https://github.com/helm/helm/issues/8038
          value: /tmp
        args:
          - -debug
          - -group={{ .apiGroup }}
          - -version={{ .apiVersion }}
          - -resource={{ .resource }}
          - -namespace={{ .namespace }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   privileged: false
        #   runAsGroup: 2000
        #   runAsNonRoot: true
        #   runAsUser: 2000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      # securityContext:
      #   runAsGroup: 2000
      #   runAsNonRoot: true
      #   runAsUser: 2000
      serviceAccount: {{ .name }}
      serviceAccountName: {{ .name }}
      terminationGracePeriodSeconds: 30